import boidTools.util as util
import boidResources

import os



_UserProvidedFilePath_ = None
_SAVE_FILE_EXTENSION_ = ".pkl"
_DEFAULT_VALUES_FILENAME_ = "attributeValueDefaults.ini"



#############################
def SetSaveLocation(filePath):
    _UserProvidedFilePath_ = filePath
    
    util.LogInfo("Set save-file path to: %s" % (_UserProvidedFilePath_ 
                                                if(HaveUserProvidedSavePath()) else
                                                "Auto-generated."))

####
def HaveUserProvidedSavePath():
    if(_UserProvidedFilePath_ is not None and _UserProvidedFilePath_):
        return True
    else:
        return False

####
def SaveFileLocation():
    if(HaveUserProvidedSavePath()):
        return _UserProvidedFilePath_
    else:
        return os.path.join(SaveFolderLocation(), 
                            ("%s_%s%s" % (util.GetCurrentSceneName(), util.PackageName(), SaveFileExtension())))

#####
def _AutoGeneratedSavePath():
    folderPath = util.GetProjectRootDirectory()
    if(folderPath is not None and folderPath):
        folderPath = os.path.join(folderPath, "scripts" + os.path.sep)
        if(os.path.exists(folderPath)):
            return folderPath
    else:
        raise RuntimeError("Could not find \"scripts\" folder in your Maya project database. ")
                
#####
def SaveFolderLocation():
    try:
        if(HaveUserProvidedSavePath()):
            folderPath = os.path.split(_UserProvidedFilePath_)[0]
            if(folderPath is not None and folderPath):
                return folderPath
            else:
                raise RuntimeError("\"%s\" is not a valid filepath. " % _UserProvidedFilePath_)
        else:
            return _AutoGeneratedSavePath()
    except RuntimeError as e:
        util.LogWarning(e + ("Using path:" % util.GetProjectWorkingDirectory()))
    
    return util.GetProjectWorkingDirectory()

#####
def SaveFileExtension():
    return _SAVE_FILE_EXTENSION_

##########################################
def DefaultAttributeValuesLocation():
    filePath = os.path.dirname(boidResources.__file__)
    return os.path.join(filePath, _DEFAULT_VALUES_FILENAME_)


# END OF MODULE
#############################################